DROP DATABASE IF EXISTS ESCUELA;
CREATE DATABASE IF NOT EXISTS ESCUELA;
USE ESCUELA;

CREATE TABLE IF NOT EXISTS ALUMNO (
  NIF VARCHAR(9) PRIMARY KEY,
  NOMBRE VARCHAR(20),
  TRABAJA BOOLEAN,
  ESTUDIOS SET('ESO', 'BACHILLERATO', 'FP MEDIO', 'FP SUPERIOR', 'GRADO SUPERIOR'),
  INGRESOS DECIMAL(9,2),
  FECHA_NACIMIENTO DATE
);
INSERT INTO ALUMNO (NIF, NOMBRE, TRABAJA, ESTUDIOS, INGRESOS, FECHA_NACIMIENTO)
VALUES
('12345678F', 'ALEX', TRUE, 'BACHILLERATO', 1500.15, '2003-04-30'),
('87654321D', 'RAFA', FALSE, 'FP MEDIO', 2500.75, '2000-06-27'),
('45637281L', 'MARCOS', TRUE, 'BACHILLERATO', 0, '2003-11-27'),
('87634509G', 'IKER', FALSE, 'FP SUPERIOR', 5000.99, '2003-06-28');

SELECT * FROM ALUMNO; -- LA TABLA
SELECT DISTINCT ESTUDIOS FROM ALUMNO; -- CURSOS QUE IMPARTO
SELECT * FROM ALUMNO ORDER BY ESTUDIOS DESC; -- ORDENADOR POR ESTUDIOS
SELECT CONCAT(NOMBRE, ' ESTUDIÓ ', ESTUDIOS) AS INFO_ALUMNOTRABAJO FROM ALUMNO;
SELECT substring(NOMBRE, 1, 3) AS PARTE_NOMBRE FROM ALUMNO;
-- SELECT CONCAT(INFO_ALUMNOTRABAJO, ' APODO ', PARTE_NOMBRE) AS EXPERIMENTO FROM ALUMNO;-->
-- SELECT NOMBRE, INGRESOS FROM ALUMNO WHERE INGRESOS = (SELECT MAX(INGRESOS) FROM ALUMNO);--> -- BUSQUEDA DENTRO DE LA PRIMERA BUSQUEDA
-- SELECT NOMBRE FROM CLIENTES C WHERE EXISTS (SELECT 1 FROM PEDIDOS P WHERE P.CLIENTE_ID = C.CLIENTES_ID AND P.IMPORTE > 5000)--> -- PARA CONCATENAR TABLAS QUE TENGAN UN MISMO VALOR (ID CLIENTES ESTA EN VARIAS TABLAS)
-- SELECT P.IMPORTE>5000 -->